global:  
  scrape_interval: 1s
  #cada cuanto evaluar metricas para alarmas
  evaluation_interval: 1s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'spark'
    static_configs:
      - targets: ['spark-master:9108', 'spark-worker-1:9109', 'spark-worker-2:9110']
  
  #- job_name: 'airflow'
  #  metrics_path: '/metrics'
  #  basic_auth:
  #    username: 'airflow'
  #    password: 'airflow'
  #  static_configs:
  #    - targets: ['airflow-webserver:8080']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-statsd-exporter:9102']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]